default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: toya-todoapp_development

test:
  <<: *default
  database: toya-todoapp_test

production:
  <<: *default
  database: toya-todoapp_production
  username: toya-todoapp
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>